Resources:
  PersonasTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Personas
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  
  